name: SYCL Pre Commit

on:
  pull_request_target:
    # Do not run builds if changes are only in the following locations
    paths-ignore:
    - '.github/ISSUE_TEMPLATE/**'
    - '.github/CODEOWNERS'
    - '.github/workflows/sycl_update_gpu_driver.yml'
    - '.github/workflows/sycl_containers.yaml'
    - '.github/workflows/sycl_nightly.yml'
    - '.github/workflows/sycl_post_commit.yml'
    - '.github/workflows/sycl_windows_build_and_test.yml'
    - '.github/workflows/sycl_macos_build_and_test.yml'
    - 'devops/containers/**'
    - 'devops/scripts/install_drivers.sh'
    - 'devops/scripts/install_build_tools.sh'
    - 'sycl/doc/**'
    - 'sycl/gdb/**'
    - 'clang/docs/**'
    - '**.md'
    - '**.rst'

permissions:
  contents: read

jobs:
  need_check:
    name: Decide which tests could be affected by the changes
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    outputs:
      llvm: ${{ steps.changes.outputs.llvm == 'true' }}
      llvm_spirv: ${{ steps.changes.outputs.llvm_spirv == 'true' }}
      clang: ${{ steps.changes.outputs.clang == 'true' }}
      xptifw: ${{ steps.changes.outputs.xptifw == 'true' }}
      libclc: ${{ steps.changes.outputs.libclc == 'true' }}
      sycl: ${{ steps.changes.outputs.sycl == 'true' }}
    steps:
      - name: Check file changes
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: changes
        with:
          filters: |
            llvm: &llvm
              - 'llvm/**'
            llvm_spirv: &llvm_spirv
              - *llvm
              - 'llvm-spirv/**'
            clang: &clang
              - *llvm
              - 'clang/**'
            sycl_fusion: &sycl-fusion
              - *llvm
              - 'sycl-fusion/**'
            xptifw: &xptifw
              - 'xptifw/**'
            libclc: &libclc
              - *llvm_spirv
              - *clang
              - 'libclc/**'
            sycl:
              - *clang
              - *sycl-fusion
              - *llvm_spirv
              - *xptifw
              - *libclc
              - 'sycl/*'
              - 'sycl/!(test-e2e)/**'

  # This job generates matrix of tests for SYCL End-to-End tests
  test_matrix:
    name: Generate Test Matrix
    uses: ./.github/workflows/sycl_gen_test_matrix.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      lts_config: "hip_amdgpu;lin_intel;esimd_emu;cuda_aws;win_l0_gen12"

  windows_default:
    name: Windows
    needs: [test_matrix]
    if: github.repository == 'intel/llvm'
    uses: ./.github/workflows/sycl_windows_build_and_test.yml
    with:
      lts_matrix: ${{ needs.test_matrix.outputs.lts_wn_matrix }}
      build_ref: ${{ github.event.pull_request.head.sha }}
      check_llvm: ${{ needs.need_check.outputs.llvm }}
      check_llvm_spirv: ${{ needs.need_check.outputs.llvm_spirv }}
      check_clang: ${{ needs.need_check.outputs.clang }}
      check_xptifw: ${{ needs.need_check.outputs.xptifw }}
      check_libclc: ${{ needs.need_check.outputs.libclc }}
      check_sycl: ${{ needs.need_check.outputs.sycl }}
